
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: searchengine_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/searchdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=mysecretpassword

  postgres-db:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: searchdb
    volumes:
      - pg_data:/var/lib/postgresql/data

  newman:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: searchengine_newman
    volumes:
      - ./postman-tests:/etc/newman
    entrypoint: [ "newman", "run", "/etc/newman/collection.json", "-e", "/etc/newman/environment.json" ]
    depends_on:
      - web

volumes:
  pg_data: